[package]
name = "asn1-ldap"
version = "0.1.0"
authors = ["Josh <keeperofdakeys@gmail.com>"]

[lib]
path = "src/lib.rs"

[dependencies]
asn1-cereal = { path = "../asn1-rs/asn1-cereal" }
asn1-cereal-derive = { path = "../asn1-rs/asn1-cereal-derive" }
log = "^0"
env_logger = "^0"
